// Mocks generated by Mockito 5.4.6 from annotations
// in riff/test/features/auth/login/logic/cubit/login_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:riff/core/networks/api_result.dart' as _i2;
import 'package:riff/features/auth/login/data/models/login_request_body.dart'
    as _i6;
import 'package:riff/features/auth/login/data/models/login_response.dart'
    as _i5;
import 'package:riff/features/auth/login/data/repos/login_repo.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeApiResult_0<T> extends _i1.SmartFake implements _i2.ApiResult<T> {
  _FakeApiResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [LoginRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockLoginRepo extends _i1.Mock implements _i3.LoginRepo {
  MockLoginRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ApiResult<_i5.LoginResponse>> login(
    _i6.LoginRequestBody? body,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#login, [body]),
            returnValue: _i4.Future<_i2.ApiResult<_i5.LoginResponse>>.value(
              _FakeApiResult_0<_i5.LoginResponse>(
                this,
                Invocation.method(#login, [body]),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResult<_i5.LoginResponse>>);

  @override
  _i4.Future<_i2.ApiResult<_i5.LoginResponse>> loginWithGoogle(
    String? idToken,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#loginWithGoogle, [idToken]),
            returnValue: _i4.Future<_i2.ApiResult<_i5.LoginResponse>>.value(
              _FakeApiResult_0<_i5.LoginResponse>(
                this,
                Invocation.method(#loginWithGoogle, [idToken]),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResult<_i5.LoginResponse>>);
}
