// Mocks generated by Mockito 5.4.6 from annotations
// in riff/test/features/home/user_profile/logic/cubit/user_profile_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i8;
import 'package:riff/core/networks/api_result.dart' as _i2;
import 'package:riff/features/home/feed/data/models/post.dart' as _i6;
import 'package:riff/features/home/follow/data/models/follow_user.dart' as _i9;
import 'package:riff/features/home/follow/data/repos/follow_repo.dart' as _i7;
import 'package:riff/features/home/user_profile/data/models/user_profile_model.dart'
    as _i5;
import 'package:riff/features/home/user_profile/data/repos/user_profile_repo.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeApiResult_0<T> extends _i1.SmartFake implements _i2.ApiResult<T> {
  _FakeApiResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [UserProfileRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockUserProfileRepo extends _i1.Mock implements _i3.UserProfileRepo {
  MockUserProfileRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ApiResult<_i5.UserProfileModel>> getUserProfile(
    String? userId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUserProfile, [userId]),
            returnValue: _i4.Future<_i2.ApiResult<_i5.UserProfileModel>>.value(
              _FakeApiResult_0<_i5.UserProfileModel>(
                this,
                Invocation.method(#getUserProfile, [userId]),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResult<_i5.UserProfileModel>>);

  @override
  _i4.Future<_i2.ApiResult<List<_i6.Post>>> getUserPosts(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserPosts, [userId]),
            returnValue: _i4.Future<_i2.ApiResult<List<_i6.Post>>>.value(
              _FakeApiResult_0<List<_i6.Post>>(
                this,
                Invocation.method(#getUserPosts, [userId]),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResult<List<_i6.Post>>>);
}

/// A class which mocks [FollowRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockFollowRepo extends _i1.Mock implements _i7.FollowRepo {
  MockFollowRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<String> followUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#followUser, [userId]),
            returnValue: _i4.Future<String>.value(
              _i8.dummyValue<String>(
                this,
                Invocation.method(#followUser, [userId]),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<void> unfollowUser(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#unfollowUser, [userId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> acceptFollow(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#acceptFollow, [userId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> rejectFollow(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#rejectFollow, [userId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> removeFollower(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#removeFollower, [userId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> updatePrivacy(bool? isPrivate) =>
      (super.noSuchMethod(
            Invocation.method(#updatePrivacy, [isPrivate]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<List<_i9.FollowUser>> getFollowers(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getFollowers, [userId]),
            returnValue: _i4.Future<List<_i9.FollowUser>>.value(
              <_i9.FollowUser>[],
            ),
          )
          as _i4.Future<List<_i9.FollowUser>>);

  @override
  _i4.Future<List<_i9.FollowUser>> getFollowing(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getFollowing, [userId]),
            returnValue: _i4.Future<List<_i9.FollowUser>>.value(
              <_i9.FollowUser>[],
            ),
          )
          as _i4.Future<List<_i9.FollowUser>>);
}
