// Mocks generated by Mockito 5.4.6 from annotations
// in riff/test/features/home/notifications/logic/cubit/notifications_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:riff/features/home/notifications/data/models/notification_model.dart'
    as _i2;
import 'package:riff/features/home/notifications/data/repos/notifications_repo.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeNotificationsResponse_0 extends _i1.SmartFake
    implements _i2.NotificationsResponse {
  _FakeNotificationsResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [NotificationsRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockNotificationsRepo extends _i1.Mock implements _i3.NotificationsRepo {
  MockNotificationsRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.NotificationsResponse> getNotifications() =>
      (super.noSuchMethod(
            Invocation.method(#getNotifications, []),
            returnValue: _i4.Future<_i2.NotificationsResponse>.value(
              _FakeNotificationsResponse_0(
                this,
                Invocation.method(#getNotifications, []),
              ),
            ),
          )
          as _i4.Future<_i2.NotificationsResponse>);

  @override
  _i4.Future<void> markAllRead() =>
      (super.noSuchMethod(
            Invocation.method(#markAllRead, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteNotification(int? id) =>
      (super.noSuchMethod(
            Invocation.method(#deleteNotification, [id]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteAllNotifications() =>
      (super.noSuchMethod(
            Invocation.method(#deleteAllNotifications, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
