// Mocks generated by Mockito 5.4.6 from annotations
// in riff/test/features/home/feed/logic/cubit/feed_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:riff/core/networks/api_result.dart' as _i2;
import 'package:riff/features/home/feed/data/models/post.dart' as _i5;
import 'package:riff/features/home/feed/data/models/posts_response.dart' as _i6;
import 'package:riff/features/home/feed/data/repos/feed_repo.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeApiResult_0<T> extends _i1.SmartFake implements _i2.ApiResult<T> {
  _FakeApiResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [FeedRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockFeedRepo extends _i1.Mock implements _i3.FeedRepo {
  MockFeedRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ApiResult<_i5.Post>> getPostById(int? postId) =>
      (super.noSuchMethod(
            Invocation.method(#getPostById, [postId]),
            returnValue: _i4.Future<_i2.ApiResult<_i5.Post>>.value(
              _FakeApiResult_0<_i5.Post>(
                this,
                Invocation.method(#getPostById, [postId]),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResult<_i5.Post>>);

  @override
  _i4.Future<_i2.ApiResult<_i6.PostsResponse>> getPosts(
    int? page,
    int? limit,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getPosts, [page, limit]),
            returnValue: _i4.Future<_i2.ApiResult<_i6.PostsResponse>>.value(
              _FakeApiResult_0<_i6.PostsResponse>(
                this,
                Invocation.method(#getPosts, [page, limit]),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResult<_i6.PostsResponse>>);

  @override
  _i4.Future<_i2.ApiResult<_i5.Post>> sharePost(
    String? postId, {
    String? caption,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sharePost, [postId], {#caption: caption}),
            returnValue: _i4.Future<_i2.ApiResult<_i5.Post>>.value(
              _FakeApiResult_0<_i5.Post>(
                this,
                Invocation.method(#sharePost, [postId], {#caption: caption}),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResult<_i5.Post>>);

  @override
  _i4.Future<void> recordView(int? postId) =>
      (super.noSuchMethod(
            Invocation.method(#recordView, [postId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.ApiResult<_i5.Post?>> getTrendingPost() =>
      (super.noSuchMethod(
            Invocation.method(#getTrendingPost, []),
            returnValue: _i4.Future<_i2.ApiResult<_i5.Post?>>.value(
              _FakeApiResult_0<_i5.Post?>(
                this,
                Invocation.method(#getTrendingPost, []),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResult<_i5.Post?>>);
}
