// Mocks generated by Mockito 5.4.6 from annotations
// in riff/test/features/home/feed/logic/cubit/post_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:riff/core/networks/api_result.dart' as _i2;
import 'package:riff/features/home/feed/data/models/post.dart' as _i7;
import 'package:riff/features/home/feed/data/models/posts_response.dart' as _i8;
import 'package:riff/features/home/feed/data/repos/feed_repo.dart' as _i6;
import 'package:riff/features/home/feed/data/repos/like_repo.dart' as _i3;
import 'package:riff/features/home/follow/data/models/follow_user.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeApiResult_0<T> extends _i1.SmartFake implements _i2.ApiResult<T> {
  _FakeApiResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [LikeRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockLikeRepo extends _i1.Mock implements _i3.LikeRepo {
  MockLikeRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ApiResult<List<_i5.FollowUser>>> getPostLikers(int? postId) =>
      (super.noSuchMethod(
            Invocation.method(#getPostLikers, [postId]),
            returnValue: _i4.Future<_i2.ApiResult<List<_i5.FollowUser>>>.value(
              _FakeApiResult_0<List<_i5.FollowUser>>(
                this,
                Invocation.method(#getPostLikers, [postId]),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResult<List<_i5.FollowUser>>>);

  @override
  _i4.Future<_i2.ApiResult<bool>> likePost(String? postId) =>
      (super.noSuchMethod(
            Invocation.method(#likePost, [postId]),
            returnValue: _i4.Future<_i2.ApiResult<bool>>.value(
              _FakeApiResult_0<bool>(
                this,
                Invocation.method(#likePost, [postId]),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResult<bool>>);

  @override
  _i4.Future<_i2.ApiResult<bool>> unlikePost(String? postId) =>
      (super.noSuchMethod(
            Invocation.method(#unlikePost, [postId]),
            returnValue: _i4.Future<_i2.ApiResult<bool>>.value(
              _FakeApiResult_0<bool>(
                this,
                Invocation.method(#unlikePost, [postId]),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResult<bool>>);
}

/// A class which mocks [FeedRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockFeedRepo extends _i1.Mock implements _i6.FeedRepo {
  MockFeedRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ApiResult<_i7.Post>> getPostById(int? postId) =>
      (super.noSuchMethod(
            Invocation.method(#getPostById, [postId]),
            returnValue: _i4.Future<_i2.ApiResult<_i7.Post>>.value(
              _FakeApiResult_0<_i7.Post>(
                this,
                Invocation.method(#getPostById, [postId]),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResult<_i7.Post>>);

  @override
  _i4.Future<_i2.ApiResult<_i8.PostsResponse>> getPosts(
    int? page,
    int? limit,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getPosts, [page, limit]),
            returnValue: _i4.Future<_i2.ApiResult<_i8.PostsResponse>>.value(
              _FakeApiResult_0<_i8.PostsResponse>(
                this,
                Invocation.method(#getPosts, [page, limit]),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResult<_i8.PostsResponse>>);

  @override
  _i4.Future<_i2.ApiResult<_i7.Post>> sharePost(
    String? postId, {
    String? caption,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#sharePost, [postId], {#caption: caption}),
            returnValue: _i4.Future<_i2.ApiResult<_i7.Post>>.value(
              _FakeApiResult_0<_i7.Post>(
                this,
                Invocation.method(#sharePost, [postId], {#caption: caption}),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResult<_i7.Post>>);

  @override
  _i4.Future<void> recordView(int? postId) =>
      (super.noSuchMethod(
            Invocation.method(#recordView, [postId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.ApiResult<_i7.Post?>> getTrendingPost() =>
      (super.noSuchMethod(
            Invocation.method(#getTrendingPost, []),
            returnValue: _i4.Future<_i2.ApiResult<_i7.Post?>>.value(
              _FakeApiResult_0<_i7.Post?>(
                this,
                Invocation.method(#getTrendingPost, []),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResult<_i7.Post?>>);
}
