// Mocks generated by Mockito 5.4.6 from annotations
// in riff/test/features/home/profile_settings/UI/profile_settings_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:riff/core/networks/api_result.dart' as _i2;
import 'package:riff/features/home/core/data/repos/home_repo.dart' as _i3;
import 'package:riff/features/home/profile/UI/profile_screen.dart' as _i5;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeApiResult_0<T> extends _i1.SmartFake implements _i2.ApiResult<T> {
  _FakeApiResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [HomeRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockHomeRepo extends _i1.Mock implements _i3.HomeRepo {
  MockHomeRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ApiResult<_i5.UserProfile>> getMe() =>
      (super.noSuchMethod(
            Invocation.method(#getMe, []),
            returnValue: _i4.Future<_i2.ApiResult<_i5.UserProfile>>.value(
              _FakeApiResult_0<_i5.UserProfile>(
                this,
                Invocation.method(#getMe, []),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResult<_i5.UserProfile>>);

  @override
  _i4.Future<_i2.ApiResult<bool>> checkUsername(String? username) =>
      (super.noSuchMethod(
            Invocation.method(#checkUsername, [username]),
            returnValue: _i4.Future<_i2.ApiResult<bool>>.value(
              _FakeApiResult_0<bool>(
                this,
                Invocation.method(#checkUsername, [username]),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResult<bool>>);

  @override
  _i4.Future<_i2.ApiResult<void>> changePassword({
    required String? oldPassword,
    required String? newPassword,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#changePassword, [], {
              #oldPassword: oldPassword,
              #newPassword: newPassword,
            }),
            returnValue: _i4.Future<_i2.ApiResult<void>>.value(
              _FakeApiResult_0<void>(
                this,
                Invocation.method(#changePassword, [], {
                  #oldPassword: oldPassword,
                  #newPassword: newPassword,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResult<void>>);

  @override
  _i4.Future<_i2.ApiResult<void>> updateProfile({
    String? fullName,
    String? username,
    String? email,
    List<String>? genres,
    List<String>? instruments,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [], {
              #fullName: fullName,
              #username: username,
              #email: email,
              #genres: genres,
              #instruments: instruments,
            }),
            returnValue: _i4.Future<_i2.ApiResult<void>>.value(
              _FakeApiResult_0<void>(
                this,
                Invocation.method(#updateProfile, [], {
                  #fullName: fullName,
                  #username: username,
                  #email: email,
                  #genres: genres,
                  #instruments: instruments,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResult<void>>);
}
