// Mocks generated by Mockito 5.4.6 from annotations
// in riff/test/features/home/reels/logic/cubit/reels_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:riff/core/networks/api_result.dart' as _i2;
import 'package:riff/features/home/feed/data/models/posts_response.dart' as _i5;
import 'package:riff/features/home/reels/data/repos/reels_repo.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeApiResult_0<T> extends _i1.SmartFake implements _i2.ApiResult<T> {
  _FakeApiResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ReelsRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockReelsRepo extends _i1.Mock implements _i3.ReelsRepo {
  MockReelsRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ApiResult<_i5.PostsResponse>> getReels(
    int? page,
    int? limit,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getReels, [page, limit]),
            returnValue: _i4.Future<_i2.ApiResult<_i5.PostsResponse>>.value(
              _FakeApiResult_0<_i5.PostsResponse>(
                this,
                Invocation.method(#getReels, [page, limit]),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResult<_i5.PostsResponse>>);
}
