// Mocks generated by Mockito 5.4.6 from annotations
// in riff/test/features/home/feed/data/repos/like_repo_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i7;

import 'package:dio/dio.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:retrofit/retrofit.dart' as _i2;
import 'package:riff/core/networks/api_services.dart' as _i6;
import 'package:riff/features/auth/forgot_password/data/models/request_otp_request_body.dart'
    as _i10;
import 'package:riff/features/auth/forgot_password/data/models/reset_password_request_body.dart'
    as _i12;
import 'package:riff/features/auth/forgot_password/data/models/verify_otp_request_body.dart'
    as _i11;
import 'package:riff/features/auth/login/data/models/google_auth_request_body.dart'
    as _i13;
import 'package:riff/features/auth/login/data/models/login_request_body.dart'
    as _i8;
import 'package:riff/features/auth/signup/data/models/signup_request_body.dart'
    as _i9;
import 'package:riff/features/home/add_post/data/models/create_post_request_model.dart'
    as _i14;
import 'package:riff/features/home/feed/data/models/comment.dart' as _i15;
import 'package:riff/features/home/feed/data/models/create_comment_request_model.dart'
    as _i16;
import 'package:riff/features/home/feed/data/models/post.dart' as _i4;
import 'package:riff/features/home/feed/data/models/posts_response.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeHttpResponse_0<T> extends _i1.SmartFake
    implements _i2.HttpResponse<T> {
  _FakeHttpResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePostsResponse_1 extends _i1.SmartFake implements _i3.PostsResponse {
  _FakePostsResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakePost_2 extends _i1.SmartFake implements _i4.Post {
  _FakePost_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeBaseOptions_3 extends _i1.SmartFake implements _i5.BaseOptions {
  _FakeBaseOptions_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeInterceptors_4 extends _i1.SmartFake implements _i5.Interceptors {
  _FakeInterceptors_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHttpClientAdapter_5 extends _i1.SmartFake
    implements _i5.HttpClientAdapter {
  _FakeHttpClientAdapter_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeTransformer_6 extends _i1.SmartFake implements _i5.Transformer {
  _FakeTransformer_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponse_7<T1> extends _i1.SmartFake implements _i5.Response<T1> {
  _FakeResponse_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeDio_8 extends _i1.SmartFake implements _i5.Dio {
  _FakeDio_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i6.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.Future<_i2.HttpResponse<dynamic>> login(
    _i8.LoginRequestBody? loginRequestBody,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#login, [loginRequestBody]),
            returnValue: _i7.Future<_i2.HttpResponse<dynamic>>.value(
              _FakeHttpResponse_0<dynamic>(
                this,
                Invocation.method(#login, [loginRequestBody]),
              ),
            ),
          )
          as _i7.Future<_i2.HttpResponse<dynamic>>);

  @override
  _i7.Future<void> signUp(_i9.SignupRequestBody? signupRequestBody) =>
      (super.noSuchMethod(
            Invocation.method(#signUp, [signupRequestBody]),
            returnValue: _i7.Future<void>.value(),
            returnValueForMissingStub: _i7.Future<void>.value(),
          )
          as _i7.Future<void>);

  @override
  _i7.Future<_i2.HttpResponse<void>> refreshToken() =>
      (super.noSuchMethod(
            Invocation.method(#refreshToken, []),
            returnValue: _i7.Future<_i2.HttpResponse<void>>.value(
              _FakeHttpResponse_0<void>(
                this,
                Invocation.method(#refreshToken, []),
              ),
            ),
          )
          as _i7.Future<_i2.HttpResponse<void>>);

  @override
  _i7.Future<_i2.HttpResponse<void>> requestOtp(
    _i10.RequestOtpRequestBody? requestOtpRequestBody,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#requestOtp, [requestOtpRequestBody]),
            returnValue: _i7.Future<_i2.HttpResponse<void>>.value(
              _FakeHttpResponse_0<void>(
                this,
                Invocation.method(#requestOtp, [requestOtpRequestBody]),
              ),
            ),
          )
          as _i7.Future<_i2.HttpResponse<void>>);

  @override
  _i7.Future<_i2.HttpResponse<void>> verifyOtp(
    _i11.VerifyOtpRequestBody? verifyOtpRequestBody,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#verifyOtp, [verifyOtpRequestBody]),
            returnValue: _i7.Future<_i2.HttpResponse<void>>.value(
              _FakeHttpResponse_0<void>(
                this,
                Invocation.method(#verifyOtp, [verifyOtpRequestBody]),
              ),
            ),
          )
          as _i7.Future<_i2.HttpResponse<void>>);

  @override
  _i7.Future<_i2.HttpResponse<void>> resetPassword(
    _i12.ResetPasswordRequestBody? resetPasswordRequestBody,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [resetPasswordRequestBody]),
            returnValue: _i7.Future<_i2.HttpResponse<void>>.value(
              _FakeHttpResponse_0<void>(
                this,
                Invocation.method(#resetPassword, [resetPasswordRequestBody]),
              ),
            ),
          )
          as _i7.Future<_i2.HttpResponse<void>>);

  @override
  _i7.Future<_i2.HttpResponse<dynamic>> googleLogin(
    _i13.GoogleAuthRequestBody? body,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#googleLogin, [body]),
            returnValue: _i7.Future<_i2.HttpResponse<dynamic>>.value(
              _FakeHttpResponse_0<dynamic>(
                this,
                Invocation.method(#googleLogin, [body]),
              ),
            ),
          )
          as _i7.Future<_i2.HttpResponse<dynamic>>);

  @override
  _i7.Future<_i2.HttpResponse<dynamic>> getUser() =>
      (super.noSuchMethod(
            Invocation.method(#getUser, []),
            returnValue: _i7.Future<_i2.HttpResponse<dynamic>>.value(
              _FakeHttpResponse_0<dynamic>(
                this,
                Invocation.method(#getUser, []),
              ),
            ),
          )
          as _i7.Future<_i2.HttpResponse<dynamic>>);

  @override
  _i7.Future<_i2.HttpResponse<dynamic>> getUserById(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#getUserById, [userId]),
            returnValue: _i7.Future<_i2.HttpResponse<dynamic>>.value(
              _FakeHttpResponse_0<dynamic>(
                this,
                Invocation.method(#getUserById, [userId]),
              ),
            ),
          )
          as _i7.Future<_i2.HttpResponse<dynamic>>);

  @override
  _i7.Future<_i3.PostsResponse> getPosts(int? page, int? limit) =>
      (super.noSuchMethod(
            Invocation.method(#getPosts, [page, limit]),
            returnValue: _i7.Future<_i3.PostsResponse>.value(
              _FakePostsResponse_1(
                this,
                Invocation.method(#getPosts, [page, limit]),
              ),
            ),
          )
          as _i7.Future<_i3.PostsResponse>);

  @override
  _i7.Future<_i4.Post> createPost(
    _i14.CreatePostRequestModel? createPostRequestModel,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createPost, [createPostRequestModel]),
            returnValue: _i7.Future<_i4.Post>.value(
              _FakePost_2(
                this,
                Invocation.method(#createPost, [createPostRequestModel]),
              ),
            ),
          )
          as _i7.Future<_i4.Post>);

  @override
  _i7.Future<_i2.HttpResponse<dynamic>> updatePost(
    String? postId,
    _i14.CreatePostRequestModel? updatePostRequestModel,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updatePost, [postId, updatePostRequestModel]),
            returnValue: _i7.Future<_i2.HttpResponse<dynamic>>.value(
              _FakeHttpResponse_0<dynamic>(
                this,
                Invocation.method(#updatePost, [
                  postId,
                  updatePostRequestModel,
                ]),
              ),
            ),
          )
          as _i7.Future<_i2.HttpResponse<dynamic>>);

  @override
  _i7.Future<_i2.HttpResponse<dynamic>> getPostById(int? postId) =>
      (super.noSuchMethod(
            Invocation.method(#getPostById, [postId]),
            returnValue: _i7.Future<_i2.HttpResponse<dynamic>>.value(
              _FakeHttpResponse_0<dynamic>(
                this,
                Invocation.method(#getPostById, [postId]),
              ),
            ),
          )
          as _i7.Future<_i2.HttpResponse<dynamic>>);

  @override
  _i7.Future<_i2.HttpResponse<void>> deletePost(String? postId) =>
      (super.noSuchMethod(
            Invocation.method(#deletePost, [postId]),
            returnValue: _i7.Future<_i2.HttpResponse<void>>.value(
              _FakeHttpResponse_0<void>(
                this,
                Invocation.method(#deletePost, [postId]),
              ),
            ),
          )
          as _i7.Future<_i2.HttpResponse<void>>);

  @override
  _i7.Future<_i2.HttpResponse<dynamic>> likePost(String? postId) =>
      (super.noSuchMethod(
            Invocation.method(#likePost, [postId]),
            returnValue: _i7.Future<_i2.HttpResponse<dynamic>>.value(
              _FakeHttpResponse_0<dynamic>(
                this,
                Invocation.method(#likePost, [postId]),
              ),
            ),
          )
          as _i7.Future<_i2.HttpResponse<dynamic>>);

  @override
  _i7.Future<_i2.HttpResponse<dynamic>> unlikePost(String? postId) =>
      (super.noSuchMethod(
            Invocation.method(#unlikePost, [postId]),
            returnValue: _i7.Future<_i2.HttpResponse<dynamic>>.value(
              _FakeHttpResponse_0<dynamic>(
                this,
                Invocation.method(#unlikePost, [postId]),
              ),
            ),
          )
          as _i7.Future<_i2.HttpResponse<dynamic>>);

  @override
  _i7.Future<_i2.HttpResponse<List<_i15.Comment>>> getPostComments(
    String? postId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getPostComments, [postId]),
            returnValue: _i7.Future<_i2.HttpResponse<List<_i15.Comment>>>.value(
              _FakeHttpResponse_0<List<_i15.Comment>>(
                this,
                Invocation.method(#getPostComments, [postId]),
              ),
            ),
          )
          as _i7.Future<_i2.HttpResponse<List<_i15.Comment>>>);

  @override
  _i7.Future<_i2.HttpResponse<_i15.Comment>> createComment(
    String? postId,
    _i16.CreateCommentRequestModel? body,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createComment, [postId, body]),
            returnValue: _i7.Future<_i2.HttpResponse<_i15.Comment>>.value(
              _FakeHttpResponse_0<_i15.Comment>(
                this,
                Invocation.method(#createComment, [postId, body]),
              ),
            ),
          )
          as _i7.Future<_i2.HttpResponse<_i15.Comment>>);

  @override
  _i7.Future<_i2.HttpResponse<dynamic>> likeComment(String? commentId) =>
      (super.noSuchMethod(
            Invocation.method(#likeComment, [commentId]),
            returnValue: _i7.Future<_i2.HttpResponse<dynamic>>.value(
              _FakeHttpResponse_0<dynamic>(
                this,
                Invocation.method(#likeComment, [commentId]),
              ),
            ),
          )
          as _i7.Future<_i2.HttpResponse<dynamic>>);

  @override
  _i7.Future<_i2.HttpResponse<dynamic>> unlikeComment(String? commentId) =>
      (super.noSuchMethod(
            Invocation.method(#unlikeComment, [commentId]),
            returnValue: _i7.Future<_i2.HttpResponse<dynamic>>.value(
              _FakeHttpResponse_0<dynamic>(
                this,
                Invocation.method(#unlikeComment, [commentId]),
              ),
            ),
          )
          as _i7.Future<_i2.HttpResponse<dynamic>>);

  @override
  _i7.Future<_i2.HttpResponse<dynamic>> getCommentById(int? commentId) =>
      (super.noSuchMethod(
            Invocation.method(#getCommentById, [commentId]),
            returnValue: _i7.Future<_i2.HttpResponse<dynamic>>.value(
              _FakeHttpResponse_0<dynamic>(
                this,
                Invocation.method(#getCommentById, [commentId]),
              ),
            ),
          )
          as _i7.Future<_i2.HttpResponse<dynamic>>);

  @override
  _i7.Future<_i2.HttpResponse<dynamic>> updateComment(
    String? commentId,
    _i16.CreateCommentRequestModel? body,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateComment, [commentId, body]),
            returnValue: _i7.Future<_i2.HttpResponse<dynamic>>.value(
              _FakeHttpResponse_0<dynamic>(
                this,
                Invocation.method(#updateComment, [commentId, body]),
              ),
            ),
          )
          as _i7.Future<_i2.HttpResponse<dynamic>>);

  @override
  _i7.Future<_i2.HttpResponse<void>> deleteComment(String? commentId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteComment, [commentId]),
            returnValue: _i7.Future<_i2.HttpResponse<void>>.value(
              _FakeHttpResponse_0<void>(
                this,
                Invocation.method(#deleteComment, [commentId]),
              ),
            ),
          )
          as _i7.Future<_i2.HttpResponse<void>>);

  @override
  _i7.Future<_i3.PostsResponse> getUserPosts(
    String? userId,
    int? page,
    int? limit,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getUserPosts, [userId, page, limit]),
            returnValue: _i7.Future<_i3.PostsResponse>.value(
              _FakePostsResponse_1(
                this,
                Invocation.method(#getUserPosts, [userId, page, limit]),
              ),
            ),
          )
          as _i7.Future<_i3.PostsResponse>);

  @override
  _i7.Future<_i4.Post> sharePost(String? postId, Map<String, dynamic>? body) =>
      (super.noSuchMethod(
            Invocation.method(#sharePost, [postId, body]),
            returnValue: _i7.Future<_i4.Post>.value(
              _FakePost_2(this, Invocation.method(#sharePost, [postId, body])),
            ),
          )
          as _i7.Future<_i4.Post>);

  @override
  _i7.Future<_i2.HttpResponse<void>> recordView(int? postId) =>
      (super.noSuchMethod(
            Invocation.method(#recordView, [postId]),
            returnValue: _i7.Future<_i2.HttpResponse<void>>.value(
              _FakeHttpResponse_0<void>(
                this,
                Invocation.method(#recordView, [postId]),
              ),
            ),
          )
          as _i7.Future<_i2.HttpResponse<void>>);

  @override
  _i7.Future<_i2.HttpResponse<dynamic>> getTrendingPost() =>
      (super.noSuchMethod(
            Invocation.method(#getTrendingPost, []),
            returnValue: _i7.Future<_i2.HttpResponse<dynamic>>.value(
              _FakeHttpResponse_0<dynamic>(
                this,
                Invocation.method(#getTrendingPost, []),
              ),
            ),
          )
          as _i7.Future<_i2.HttpResponse<dynamic>>);

  @override
  _i7.Future<_i2.HttpResponse<dynamic>> checkUsername(String? username) =>
      (super.noSuchMethod(
            Invocation.method(#checkUsername, [username]),
            returnValue: _i7.Future<_i2.HttpResponse<dynamic>>.value(
              _FakeHttpResponse_0<dynamic>(
                this,
                Invocation.method(#checkUsername, [username]),
              ),
            ),
          )
          as _i7.Future<_i2.HttpResponse<dynamic>>);

  @override
  _i7.Future<_i2.HttpResponse<dynamic>> updateProfile(
    Map<String, dynamic>? body,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#updateProfile, [body]),
            returnValue: _i7.Future<_i2.HttpResponse<dynamic>>.value(
              _FakeHttpResponse_0<dynamic>(
                this,
                Invocation.method(#updateProfile, [body]),
              ),
            ),
          )
          as _i7.Future<_i2.HttpResponse<dynamic>>);

  @override
  _i7.Future<_i2.HttpResponse<dynamic>> changePassword(
    Map<String, dynamic>? body,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#changePassword, [body]),
            returnValue: _i7.Future<_i2.HttpResponse<dynamic>>.value(
              _FakeHttpResponse_0<dynamic>(
                this,
                Invocation.method(#changePassword, [body]),
              ),
            ),
          )
          as _i7.Future<_i2.HttpResponse<dynamic>>);

  @override
  _i7.Future<_i2.HttpResponse<dynamic>> deleteAccount(
    Map<String, dynamic>? body,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#deleteAccount, [body]),
            returnValue: _i7.Future<_i2.HttpResponse<dynamic>>.value(
              _FakeHttpResponse_0<dynamic>(
                this,
                Invocation.method(#deleteAccount, [body]),
              ),
            ),
          )
          as _i7.Future<_i2.HttpResponse<dynamic>>);
}

/// A class which mocks [Dio].
///
/// See the documentation for Mockito's code generation for more information.
class MockDio extends _i1.Mock implements _i5.Dio {
  MockDio() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.BaseOptions get options =>
      (super.noSuchMethod(
            Invocation.getter(#options),
            returnValue: _FakeBaseOptions_3(this, Invocation.getter(#options)),
          )
          as _i5.BaseOptions);

  @override
  _i5.Interceptors get interceptors =>
      (super.noSuchMethod(
            Invocation.getter(#interceptors),
            returnValue: _FakeInterceptors_4(
              this,
              Invocation.getter(#interceptors),
            ),
          )
          as _i5.Interceptors);

  @override
  _i5.HttpClientAdapter get httpClientAdapter =>
      (super.noSuchMethod(
            Invocation.getter(#httpClientAdapter),
            returnValue: _FakeHttpClientAdapter_5(
              this,
              Invocation.getter(#httpClientAdapter),
            ),
          )
          as _i5.HttpClientAdapter);

  @override
  _i5.Transformer get transformer =>
      (super.noSuchMethod(
            Invocation.getter(#transformer),
            returnValue: _FakeTransformer_6(
              this,
              Invocation.getter(#transformer),
            ),
          )
          as _i5.Transformer);

  @override
  set options(_i5.BaseOptions? value) => super.noSuchMethod(
    Invocation.setter(#options, value),
    returnValueForMissingStub: null,
  );

  @override
  set httpClientAdapter(_i5.HttpClientAdapter? value) => super.noSuchMethod(
    Invocation.setter(#httpClientAdapter, value),
    returnValueForMissingStub: null,
  );

  @override
  set transformer(_i5.Transformer? value) => super.noSuchMethod(
    Invocation.setter(#transformer, value),
    returnValueForMissingStub: null,
  );

  @override
  void close({bool? force = false}) => super.noSuchMethod(
    Invocation.method(#close, [], {#force: force}),
    returnValueForMissingStub: null,
  );

  @override
  _i7.Future<_i5.Response<T>> head<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i5.Options? options,
    _i5.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #head,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
              },
            ),
            returnValue: _i7.Future<_i5.Response<T>>.value(
              _FakeResponse_7<T>(
                this,
                Invocation.method(
                  #head,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                  },
                ),
              ),
            ),
          )
          as _i7.Future<_i5.Response<T>>);

  @override
  _i7.Future<_i5.Response<T>> headUri<T>(
    Uri? uri, {
    Object? data,
    _i5.Options? options,
    _i5.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #headUri,
              [uri],
              {#data: data, #options: options, #cancelToken: cancelToken},
            ),
            returnValue: _i7.Future<_i5.Response<T>>.value(
              _FakeResponse_7<T>(
                this,
                Invocation.method(
                  #headUri,
                  [uri],
                  {#data: data, #options: options, #cancelToken: cancelToken},
                ),
              ),
            ),
          )
          as _i7.Future<_i5.Response<T>>);

  @override
  _i7.Future<_i5.Response<T>> get<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i5.Options? options,
    _i5.CancelToken? cancelToken,
    _i5.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #get,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i7.Future<_i5.Response<T>>.value(
              _FakeResponse_7<T>(
                this,
                Invocation.method(
                  #get,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i7.Future<_i5.Response<T>>);

  @override
  _i7.Future<_i5.Response<T>> getUri<T>(
    Uri? uri, {
    Object? data,
    _i5.Options? options,
    _i5.CancelToken? cancelToken,
    _i5.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getUri,
              [uri],
              {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i7.Future<_i5.Response<T>>.value(
              _FakeResponse_7<T>(
                this,
                Invocation.method(
                  #getUri,
                  [uri],
                  {
                    #data: data,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i7.Future<_i5.Response<T>>);

  @override
  _i7.Future<_i5.Response<T>> post<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i5.Options? options,
    _i5.CancelToken? cancelToken,
    _i5.ProgressCallback? onSendProgress,
    _i5.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i7.Future<_i5.Response<T>>.value(
              _FakeResponse_7<T>(
                this,
                Invocation.method(
                  #post,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i7.Future<_i5.Response<T>>);

  @override
  _i7.Future<_i5.Response<T>> postUri<T>(
    Uri? uri, {
    Object? data,
    _i5.Options? options,
    _i5.CancelToken? cancelToken,
    _i5.ProgressCallback? onSendProgress,
    _i5.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #postUri,
              [uri],
              {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i7.Future<_i5.Response<T>>.value(
              _FakeResponse_7<T>(
                this,
                Invocation.method(
                  #postUri,
                  [uri],
                  {
                    #data: data,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i7.Future<_i5.Response<T>>);

  @override
  _i7.Future<_i5.Response<T>> put<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i5.Options? options,
    _i5.CancelToken? cancelToken,
    _i5.ProgressCallback? onSendProgress,
    _i5.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #put,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i7.Future<_i5.Response<T>>.value(
              _FakeResponse_7<T>(
                this,
                Invocation.method(
                  #put,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i7.Future<_i5.Response<T>>);

  @override
  _i7.Future<_i5.Response<T>> putUri<T>(
    Uri? uri, {
    Object? data,
    _i5.Options? options,
    _i5.CancelToken? cancelToken,
    _i5.ProgressCallback? onSendProgress,
    _i5.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #putUri,
              [uri],
              {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i7.Future<_i5.Response<T>>.value(
              _FakeResponse_7<T>(
                this,
                Invocation.method(
                  #putUri,
                  [uri],
                  {
                    #data: data,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i7.Future<_i5.Response<T>>);

  @override
  _i7.Future<_i5.Response<T>> patch<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i5.Options? options,
    _i5.CancelToken? cancelToken,
    _i5.ProgressCallback? onSendProgress,
    _i5.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patch,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i7.Future<_i5.Response<T>>.value(
              _FakeResponse_7<T>(
                this,
                Invocation.method(
                  #patch,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i7.Future<_i5.Response<T>>);

  @override
  _i7.Future<_i5.Response<T>> patchUri<T>(
    Uri? uri, {
    Object? data,
    _i5.Options? options,
    _i5.CancelToken? cancelToken,
    _i5.ProgressCallback? onSendProgress,
    _i5.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #patchUri,
              [uri],
              {
                #data: data,
                #options: options,
                #cancelToken: cancelToken,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i7.Future<_i5.Response<T>>.value(
              _FakeResponse_7<T>(
                this,
                Invocation.method(
                  #patchUri,
                  [uri],
                  {
                    #data: data,
                    #options: options,
                    #cancelToken: cancelToken,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i7.Future<_i5.Response<T>>);

  @override
  _i7.Future<_i5.Response<T>> delete<T>(
    String? path, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i5.Options? options,
    _i5.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [path],
              {
                #data: data,
                #queryParameters: queryParameters,
                #options: options,
                #cancelToken: cancelToken,
              },
            ),
            returnValue: _i7.Future<_i5.Response<T>>.value(
              _FakeResponse_7<T>(
                this,
                Invocation.method(
                  #delete,
                  [path],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #options: options,
                    #cancelToken: cancelToken,
                  },
                ),
              ),
            ),
          )
          as _i7.Future<_i5.Response<T>>);

  @override
  _i7.Future<_i5.Response<T>> deleteUri<T>(
    Uri? uri, {
    Object? data,
    _i5.Options? options,
    _i5.CancelToken? cancelToken,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #deleteUri,
              [uri],
              {#data: data, #options: options, #cancelToken: cancelToken},
            ),
            returnValue: _i7.Future<_i5.Response<T>>.value(
              _FakeResponse_7<T>(
                this,
                Invocation.method(
                  #deleteUri,
                  [uri],
                  {#data: data, #options: options, #cancelToken: cancelToken},
                ),
              ),
            ),
          )
          as _i7.Future<_i5.Response<T>>);

  @override
  _i7.Future<_i5.Response<dynamic>> download(
    String? urlPath,
    dynamic savePath, {
    _i5.ProgressCallback? onReceiveProgress,
    Map<String, dynamic>? queryParameters,
    _i5.CancelToken? cancelToken,
    bool? deleteOnError = true,
    _i5.FileAccessMode? fileAccessMode = _i5.FileAccessMode.write,
    String? lengthHeader = 'content-length',
    Object? data,
    _i5.Options? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #download,
              [urlPath, savePath],
              {
                #onReceiveProgress: onReceiveProgress,
                #queryParameters: queryParameters,
                #cancelToken: cancelToken,
                #deleteOnError: deleteOnError,
                #fileAccessMode: fileAccessMode,
                #lengthHeader: lengthHeader,
                #data: data,
                #options: options,
              },
            ),
            returnValue: _i7.Future<_i5.Response<dynamic>>.value(
              _FakeResponse_7<dynamic>(
                this,
                Invocation.method(
                  #download,
                  [urlPath, savePath],
                  {
                    #onReceiveProgress: onReceiveProgress,
                    #queryParameters: queryParameters,
                    #cancelToken: cancelToken,
                    #deleteOnError: deleteOnError,
                    #fileAccessMode: fileAccessMode,
                    #lengthHeader: lengthHeader,
                    #data: data,
                    #options: options,
                  },
                ),
              ),
            ),
          )
          as _i7.Future<_i5.Response<dynamic>>);

  @override
  _i7.Future<_i5.Response<dynamic>> downloadUri(
    Uri? uri,
    dynamic savePath, {
    _i5.ProgressCallback? onReceiveProgress,
    _i5.CancelToken? cancelToken,
    bool? deleteOnError = true,
    _i5.FileAccessMode? fileAccessMode = _i5.FileAccessMode.write,
    String? lengthHeader = 'content-length',
    Object? data,
    _i5.Options? options,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #downloadUri,
              [uri, savePath],
              {
                #onReceiveProgress: onReceiveProgress,
                #cancelToken: cancelToken,
                #deleteOnError: deleteOnError,
                #fileAccessMode: fileAccessMode,
                #lengthHeader: lengthHeader,
                #data: data,
                #options: options,
              },
            ),
            returnValue: _i7.Future<_i5.Response<dynamic>>.value(
              _FakeResponse_7<dynamic>(
                this,
                Invocation.method(
                  #downloadUri,
                  [uri, savePath],
                  {
                    #onReceiveProgress: onReceiveProgress,
                    #cancelToken: cancelToken,
                    #deleteOnError: deleteOnError,
                    #fileAccessMode: fileAccessMode,
                    #lengthHeader: lengthHeader,
                    #data: data,
                    #options: options,
                  },
                ),
              ),
            ),
          )
          as _i7.Future<_i5.Response<dynamic>>);

  @override
  _i7.Future<_i5.Response<T>> request<T>(
    String? url, {
    Object? data,
    Map<String, dynamic>? queryParameters,
    _i5.CancelToken? cancelToken,
    _i5.Options? options,
    _i5.ProgressCallback? onSendProgress,
    _i5.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #request,
              [url],
              {
                #data: data,
                #queryParameters: queryParameters,
                #cancelToken: cancelToken,
                #options: options,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i7.Future<_i5.Response<T>>.value(
              _FakeResponse_7<T>(
                this,
                Invocation.method(
                  #request,
                  [url],
                  {
                    #data: data,
                    #queryParameters: queryParameters,
                    #cancelToken: cancelToken,
                    #options: options,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i7.Future<_i5.Response<T>>);

  @override
  _i7.Future<_i5.Response<T>> requestUri<T>(
    Uri? uri, {
    Object? data,
    _i5.CancelToken? cancelToken,
    _i5.Options? options,
    _i5.ProgressCallback? onSendProgress,
    _i5.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #requestUri,
              [uri],
              {
                #data: data,
                #cancelToken: cancelToken,
                #options: options,
                #onSendProgress: onSendProgress,
                #onReceiveProgress: onReceiveProgress,
              },
            ),
            returnValue: _i7.Future<_i5.Response<T>>.value(
              _FakeResponse_7<T>(
                this,
                Invocation.method(
                  #requestUri,
                  [uri],
                  {
                    #data: data,
                    #cancelToken: cancelToken,
                    #options: options,
                    #onSendProgress: onSendProgress,
                    #onReceiveProgress: onReceiveProgress,
                  },
                ),
              ),
            ),
          )
          as _i7.Future<_i5.Response<T>>);

  @override
  _i7.Future<_i5.Response<T>> fetch<T>(_i5.RequestOptions? requestOptions) =>
      (super.noSuchMethod(
            Invocation.method(#fetch, [requestOptions]),
            returnValue: _i7.Future<_i5.Response<T>>.value(
              _FakeResponse_7<T>(
                this,
                Invocation.method(#fetch, [requestOptions]),
              ),
            ),
          )
          as _i7.Future<_i5.Response<T>>);

  @override
  _i5.Dio clone({
    _i5.BaseOptions? options,
    _i5.Interceptors? interceptors,
    _i5.HttpClientAdapter? httpClientAdapter,
    _i5.Transformer? transformer,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#clone, [], {
              #options: options,
              #interceptors: interceptors,
              #httpClientAdapter: httpClientAdapter,
              #transformer: transformer,
            }),
            returnValue: _FakeDio_8(
              this,
              Invocation.method(#clone, [], {
                #options: options,
                #interceptors: interceptors,
                #httpClientAdapter: httpClientAdapter,
                #transformer: transformer,
              }),
            ),
          )
          as _i5.Dio);
}
