// Mocks generated by Mockito 5.4.6 from annotations
// in riff/test/features/auth/forgot_password/logic/cubit/forgot_password_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:riff/core/networks/api_result.dart' as _i2;
import 'package:riff/features/auth/forgot_password/data/models/request_otp_request_body.dart'
    as _i5;
import 'package:riff/features/auth/forgot_password/data/models/reset_password_request_body.dart'
    as _i7;
import 'package:riff/features/auth/forgot_password/data/models/verify_otp_request_body.dart'
    as _i6;
import 'package:riff/features/auth/forgot_password/data/repos/forgot_pasword_repo.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeApiResult_0<T> extends _i1.SmartFake implements _i2.ApiResult<T> {
  _FakeApiResult_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ForgotPasswordRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockForgotPasswordRepo extends _i1.Mock
    implements _i3.ForgotPasswordRepo {
  MockForgotPasswordRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.ApiResult<String?>> requestOtp(
    _i5.RequestOtpRequestBody? requestOtpRequestBody,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#requestOtp, [requestOtpRequestBody]),
            returnValue: _i4.Future<_i2.ApiResult<String?>>.value(
              _FakeApiResult_0<String?>(
                this,
                Invocation.method(#requestOtp, [requestOtpRequestBody]),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResult<String?>>);

  @override
  _i4.Future<_i2.ApiResult<String?>> verifyOtp(
    _i6.VerifyOtpRequestBody? verifyOtpRequestBody,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#verifyOtp, [verifyOtpRequestBody]),
            returnValue: _i4.Future<_i2.ApiResult<String?>>.value(
              _FakeApiResult_0<String?>(
                this,
                Invocation.method(#verifyOtp, [verifyOtpRequestBody]),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResult<String?>>);

  @override
  _i4.Future<_i2.ApiResult<void>> resetPassword(
    _i7.ResetPasswordRequestBody? resetPasswordRequestBody,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [resetPasswordRequestBody]),
            returnValue: _i4.Future<_i2.ApiResult<void>>.value(
              _FakeApiResult_0<void>(
                this,
                Invocation.method(#resetPassword, [resetPasswordRequestBody]),
              ),
            ),
          )
          as _i4.Future<_i2.ApiResult<void>>);
}
