// Mocks generated by Mockito 5.4.6 from annotations
// in riff/test/features/home/chat/logic/cubit/chats_list_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i5;
import 'package:riff/features/home/chat/data/models/chat_models.dart' as _i2;
import 'package:riff/features/home/chat/data/repos/chat_repo.dart' as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeConversation_0 extends _i1.SmartFake implements _i2.Conversation {
  _FakeConversation_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeChatMessage_1 extends _i1.SmartFake implements _i2.ChatMessage {
  _FakeChatMessage_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ChatRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockChatRepo extends _i1.Mock implements _i3.ChatRepo {
  MockChatRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Conversation> getConversationById(String? id) =>
      (super.noSuchMethod(
            Invocation.method(#getConversationById, [id]),
            returnValue: _i4.Future<_i2.Conversation>.value(
              _FakeConversation_0(
                this,
                Invocation.method(#getConversationById, [id]),
              ),
            ),
          )
          as _i4.Future<_i2.Conversation>);

  @override
  _i4.Future<List<_i2.Conversation>> getConversations() =>
      (super.noSuchMethod(
            Invocation.method(#getConversations, []),
            returnValue: _i4.Future<List<_i2.Conversation>>.value(
              <_i2.Conversation>[],
            ),
          )
          as _i4.Future<List<_i2.Conversation>>);

  @override
  _i4.Future<List<_i2.Conversation>> getMessageRequests() =>
      (super.noSuchMethod(
            Invocation.method(#getMessageRequests, []),
            returnValue: _i4.Future<List<_i2.Conversation>>.value(
              <_i2.Conversation>[],
            ),
          )
          as _i4.Future<List<_i2.Conversation>>);

  @override
  _i4.Future<_i2.Conversation> startDirectConversation(String? userId) =>
      (super.noSuchMethod(
            Invocation.method(#startDirectConversation, [userId]),
            returnValue: _i4.Future<_i2.Conversation>.value(
              _FakeConversation_0(
                this,
                Invocation.method(#startDirectConversation, [userId]),
              ),
            ),
          )
          as _i4.Future<_i2.Conversation>);

  @override
  _i4.Future<_i2.Conversation> createGroupConversation({
    required String? name,
    String? description,
    String? imageUrl,
    required List<String>? memberIds,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#createGroupConversation, [], {
              #name: name,
              #description: description,
              #imageUrl: imageUrl,
              #memberIds: memberIds,
            }),
            returnValue: _i4.Future<_i2.Conversation>.value(
              _FakeConversation_0(
                this,
                Invocation.method(#createGroupConversation, [], {
                  #name: name,
                  #description: description,
                  #imageUrl: imageUrl,
                  #memberIds: memberIds,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.Conversation>);

  @override
  _i4.Future<List<_i2.ChatMessage>> getMessages(
    String? conversationId, {
    String? beforeId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #getMessages,
              [conversationId],
              {#beforeId: beforeId},
            ),
            returnValue: _i4.Future<List<_i2.ChatMessage>>.value(
              <_i2.ChatMessage>[],
            ),
          )
          as _i4.Future<List<_i2.ChatMessage>>);

  @override
  _i4.Future<String> uploadGroupPhoto(String? filePath, String? fileName) =>
      (super.noSuchMethod(
            Invocation.method(#uploadGroupPhoto, [filePath, fileName]),
            returnValue: _i4.Future<String>.value(
              _i5.dummyValue<String>(
                this,
                Invocation.method(#uploadGroupPhoto, [filePath, fileName]),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<_i2.ChatMessage> uploadMedia(
    String? conversationId,
    String? filePath,
    String? fileName,
    String? mimeType, {
    int? duration,
    String? clientId,
    String? replyToId,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #uploadMedia,
              [conversationId, filePath, fileName, mimeType],
              {#duration: duration, #clientId: clientId, #replyToId: replyToId},
            ),
            returnValue: _i4.Future<_i2.ChatMessage>.value(
              _FakeChatMessage_1(
                this,
                Invocation.method(
                  #uploadMedia,
                  [conversationId, filePath, fileName, mimeType],
                  {
                    #duration: duration,
                    #clientId: clientId,
                    #replyToId: replyToId,
                  },
                ),
              ),
            ),
          )
          as _i4.Future<_i2.ChatMessage>);

  @override
  _i4.Future<void> acceptRequest(String? conversationId) =>
      (super.noSuchMethod(
            Invocation.method(#acceptRequest, [conversationId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> declineRequest(String? conversationId) =>
      (super.noSuchMethod(
            Invocation.method(#declineRequest, [conversationId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> deleteMessage(String? conversationId, String? messageId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteMessage, [conversationId, messageId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.ChatMessage> editMessage(
    String? conversationId,
    String? messageId,
    String? content,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#editMessage, [
              conversationId,
              messageId,
              content,
            ]),
            returnValue: _i4.Future<_i2.ChatMessage>.value(
              _FakeChatMessage_1(
                this,
                Invocation.method(#editMessage, [
                  conversationId,
                  messageId,
                  content,
                ]),
              ),
            ),
          )
          as _i4.Future<_i2.ChatMessage>);

  @override
  _i4.Future<List<_i2.MessageReaction>> reactToMessage(
    String? conversationId,
    String? messageId,
    String? emoji,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#reactToMessage, [
              conversationId,
              messageId,
              emoji,
            ]),
            returnValue: _i4.Future<List<_i2.MessageReaction>>.value(
              <_i2.MessageReaction>[],
            ),
          )
          as _i4.Future<List<_i2.MessageReaction>>);

  @override
  _i4.Future<List<_i2.MessageReaction>> removeReaction(
    String? conversationId,
    String? messageId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#removeReaction, [conversationId, messageId]),
            returnValue: _i4.Future<List<_i2.MessageReaction>>.value(
              <_i2.MessageReaction>[],
            ),
          )
          as _i4.Future<List<_i2.MessageReaction>>);

  @override
  _i4.Future<void> deleteConversation(String? conversationId) =>
      (super.noSuchMethod(
            Invocation.method(#deleteConversation, [conversationId]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.Conversation> updateGroup(
    String? conversationId, {
    String? name,
    String? description,
    String? imageUrl,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #updateGroup,
              [conversationId],
              {#name: name, #description: description, #imageUrl: imageUrl},
            ),
            returnValue: _i4.Future<_i2.Conversation>.value(
              _FakeConversation_0(
                this,
                Invocation.method(
                  #updateGroup,
                  [conversationId],
                  {#name: name, #description: description, #imageUrl: imageUrl},
                ),
              ),
            ),
          )
          as _i4.Future<_i2.Conversation>);
}
