// Mocks generated by Mockito 5.4.6 from annotations
// in riff/test/features/home/chat/logic/cubit/user_search_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:riff/features/home/feed/data/models/post.dart' as _i5;
import 'package:riff/features/home/search/data/models/search_user.dart' as _i4;
import 'package:riff/features/home/search/data/repos/search_repo.dart' as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [SearchRepo].
///
/// See the documentation for Mockito's code generation for more information.
class MockSearchRepo extends _i1.Mock implements _i2.SearchRepo {
  MockSearchRepo() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<List<_i4.SearchUser>> searchUsers(String? q) =>
      (super.noSuchMethod(
            Invocation.method(#searchUsers, [q]),
            returnValue: _i3.Future<List<_i4.SearchUser>>.value(
              <_i4.SearchUser>[],
            ),
          )
          as _i3.Future<List<_i4.SearchUser>>);

  @override
  _i3.Future<List<_i5.Post>> searchPosts(String? q) =>
      (super.noSuchMethod(
            Invocation.method(#searchPosts, [q]),
            returnValue: _i3.Future<List<_i5.Post>>.value(<_i5.Post>[]),
          )
          as _i3.Future<List<_i5.Post>>);

  @override
  _i3.Future<List<_i5.Post>> discoverPosts({
    String? genre,
    String? instrument,
    int? page = 1,
    int? limit = 30,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#discoverPosts, [], {
              #genre: genre,
              #instrument: instrument,
              #page: page,
              #limit: limit,
            }),
            returnValue: _i3.Future<List<_i5.Post>>.value(<_i5.Post>[]),
          )
          as _i3.Future<List<_i5.Post>>);
}
